### PR TITLE
Add dependencies to setup.py

### LINKED ISSUE #103: Tell pip about necessary dependencies
Currently, running `import spinmob` in a fresh venv with only spinmob installed will error due to https://github.com/Spinmob/spinmob/blob/0edf03fc728cc960b73f4aa769752b4508dfbc78/__init__.py#L3

Resolving this, we error on https://github.com/Spinmob/spinmob/blob/0edf03fc728cc960b73f4aa769752b4508dfbc78/_data.py#L6

Next, on https://github.com/Spinmob/spinmob/blob/0edf03fc728cc960b73f4aa769752b4508dfbc78/_thread.py#L1

And et cetera.

Not everyone uses conda with preinstalled packages, so `setup.py` should tell pip to install necessary dependencies instead of requiring the user to visit the [wiki](https://github.com/Spinmob/spinmob/wiki/Home/e8211c6ee866cd2843a5efabf05008f9f3d1148c#2-install-spinmob) in order to learn of the dependencies needed to use spinmob.

Fixing this would also remove the need to check pyqtgraph versions in code since it would be handled by the package manager instead: https://github.com/Spinmob/spinmob/blob/0edf03fc728cc960b73f4aa769752b4508dfbc78/__init__.py#L45-L49

### PR DESCRIPTION
**Pull request by gschaffner**
Closes #103. Follows up on discussion in #104.

Hopefully this is the correct list of dependencies to add. Tests pass in a fresh venv with this set of dependencies, at least.

The dependencies listed on the wiki are: `scipy matplotlib lmfit pyqtgraph pyopengl spyder`.

As far as I can tell, `spyder` and `pyopengl` are not required for spinmob to operate.

When importing `pyqtgraph`, it errors with `Exception: PyQtGraph requires one of PyQt4, PyQt5, PySide or PySide2; none of these packages could be imported.`. So I've added `pyqt5` to the dependencies to fix this. This is somewhat hacky since it makes the choice of Python Qt bindings for the user, so we can remove this bit if you want.

Thanks for your time :)

### CODE REVIEW

**Comment by gschaffner** [comment]
Bump @jaxankey

**Comment by jaxankey** [comment]
The problem with this is not everyone uses strictly conda or pip to install spinmob, and I worry this "intelligent" automatic stuff can mess up a conda install. People have different PyQt environments, too. 

It's annoying, but I think implementing this would take a lot of cross-platform scenario testing? If you know more I'm all ears. I don't have a lot of time to research it, and really don't want to cause people pain installing.

Every year or two I also try to install everything without conda (or on miniconda) using pip. So far, there's always some silly problem.

**Comment by jaxankey** [comment]
In the least, we could maybe include all the dependencies that cannot be found on conda, but that just changes one of the two install commands in the instructions a bit; not a huge time-saver.

**Comment by jaxankey** [comment]
I also remember needing pyopengl for some silly reason on Linux some time ago. I don't remember why, but it may involve some older version of spyder / ipython.

**Comment by gschaffner** [comment]
> Every year or two I also try to install everything without conda (or on miniconda) using pip. So far, there's always some silly problem.

Ah! This PR is intended to fix that problem, so that spinmob's packaging makes it installable by pip without requiring copy-pasting a list of manual commands. In our group, much of our code is tested by CI, and pip is used exclusively (no conda) for setting up that environment. Currently we need some extra lines in our config files to get around the fact that spinmob's packaging doesn't actually tell the package manager about all of its dependencies. From our perspective, spinmob is the one holdout while everything else works nicely with pip already :)

If you think that this is too much friction, though, we can just keep using a workaround on our end.

> I worry this "intelligent" automatic stuff can mess up a conda install.

I don't think that this PR would mess up conda installs, since it only adds to spinmob's official dependencies packages that spinmob users would already have installed (if they install spinmob per https://github.com/Spinmob/spinmob/wiki#2-install-spinmob). (Well, pyqtgraph and lmfit are optional dependencies of spinmob, so folks might not have them installed. But they can be put in `setup.py` as optional dependencies, as I had done the first time around in https://github.com/Spinmob/spinmob/pull/104#issuecomment-724454223.)

Tons of other packages declare in `setup.py` that they have dependencies that can be installed via either conda or pip, and pip seems to see the presence of the conda packages just fine. E.g. I have had no problems with computers on which numpy is installed through conda, but pylabrad (which depends on numpy in `setup.py`) is installed through pip.

> People have different PyQt environments, too.

PyQt5 should probably not be added as a spinmob dependency, I agree. Should let users pick their choice of Python bindings for Qt.

Either way, thanks for taking the time to consider this :)

**Comment by jaxankey** [comment]
Thanks, we can give it a shot, but I would make lmfit and pyqtgraph essential first. They aren't huge and you lose a lot of functionality without them. Most people only really want the fitter interface and egg.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by gschaffner** [comment]
Awesome. Currently this PR makes lmfit and pyqtgraph essential. Should be good to merge, I think.

**Comment by jaxankey** [comment]
Pulled it and stuck it on pypi. You should try it and see what happens. For me, I created a new empty environment in conda, ran `conda install pip` then `pip install spinmob`. Things worked as expected, so I typed `python` to open the console, then `import spinmob`. As you mentioned, this produces

```
Exception: PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported.
```

So I figure "well, I could just `conda install spyder` and use whatever Qt that comes with" (note `pip install spyder` has some error with it, as is common; they can't seem to package that thing in a tidy way). After this, `import spinmob` causes

```
ImportError: cannot import name 'sip' from 'PyQt5' (/home/jack/Anaconda3/envs/test/lib/python3.9/site-packages/PyQt5/__init__.py)
```

I could try to look into this if I had time, but I do not. Is there a way to require "one of PyQt5, PyQt6, PySide2, or PySide6" or "a solid, reliable PyQt" without messing up someone's existing Qt install?

**Comment by gschaffner** [comment]
Tested the new PyPI release and it fixes the issue we were having. Thanks for merging!

I also repeated your steps (though in a fresh Python 3.9 venv instead of in a fresh conda env). Got the expected error from PyQtGraph after `pip install spinmob`. But after this, doing either `pip install pyqt5` or `pip install spyder` gets `import spinmob` working fine and with no errors on my machine.

I am not sure why `pip install spyder` doesn't get spinmob working on your machine. `pyqt5<5.13` is in Spyder's dependencies, so PyQt5 5.12.3 gets installed by `pip install spyder`. My best guess is that it's to do with your preexisting Spyder installation or conda? To narrow down if it's due to the conda vs. stdlib venv difference, maybe you can try it with a venv instead:

```bash
cd "$(mktemp -d)"
python -m venv .venv && . .venv/bin/activate
pip install spinmob
python -c 'import spinmob'
pip install spyder
python -c 'import spinmob'
```

> Is there a way to require "one of PyQt5, PyQt6, PySide2, or PySide6" or "a solid, reliable PyQt" without messing up someone's existing Qt install?

Not automatically, I don't think. Well, PyQtGraph searches for bindings and uses them if any are installed already. But if none are found, it errors and leaves the choice to the user. I don't think that spinmob can do any better than PyQtGraph does already, unless you wanted to just pick a set of bindings for the user and automatically install it as a spinmob dependency. I don't think that doing this would break anything for anyone, but IMO PyQtGraph's way of leaving the choice to users is a bit better.

> Edit: naively pip install PyQt5 breaks spyder, as you might imagine, but then spinmob works as expected.

I also do not understand why this happens. PyQt5 is already a Spyder dependency, so running `pip install pyqt5` after `pip install spyder` just gives for me

```
Requirement already satisfied: pyqt5 in ./.venv/lib/python3.9/site-packages (5.12.3)
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in ./.venv/lib/python3.9/site-packages (from pyqt5) (12.9.0)
```

**Comment by jaxankey** [comment]
The problem was probably with `conda install spyder` which is somehow not packaged correctly. Weirdly, when I do everything by pip in a new environment today, it just works, so `pip install spinmob spyder` is sufficient to get everything working.

Thanks for your help!

**Comment by jaxankey** [comment]
Do you object to including pyopengl as a requirement? The problem arises when using some of the pyqtgraph widgets that employ opengl.

**Comment by gschaffner** [comment]
No, no objections here

**Pull request merged**
