### PR TITLE
Update packaging method to tell pip about necessary dependencies

### LINKED ISSUE #103: Tell pip about necessary dependencies
Currently, running `import spinmob` in a fresh venv with only spinmob installed will error due to https://github.com/Spinmob/spinmob/blob/0edf03fc728cc960b73f4aa769752b4508dfbc78/__init__.py#L3

Resolving this, we error on https://github.com/Spinmob/spinmob/blob/0edf03fc728cc960b73f4aa769752b4508dfbc78/_data.py#L6

Next, on https://github.com/Spinmob/spinmob/blob/0edf03fc728cc960b73f4aa769752b4508dfbc78/_thread.py#L1

And et cetera.

Not everyone uses conda with preinstalled packages, so `setup.py` should tell pip to install necessary dependencies instead of requiring the user to visit the [wiki](https://github.com/Spinmob/spinmob/wiki/Home/e8211c6ee866cd2843a5efabf05008f9f3d1148c#2-install-spinmob) in order to learn of the dependencies needed to use spinmob.

Fixing this would also remove the need to check pyqtgraph versions in code since it would be handled by the package manager instead: https://github.com/Spinmob/spinmob/blob/0edf03fc728cc960b73f4aa769752b4508dfbc78/__init__.py#L45-L49

### PR DESCRIPTION
**Pull request by gschaffner**
Closes #103.

Please read the detailed commit messages when reviewing. There are a few things noted there that should be considered before merging.

If this is merged, it should be accompanied by an update of https://github.com/Spinmob/spinmob/wiki/Home.

All tests pass on Linux.

### CODE REVIEW

**Comment by gschaffner** [comment]
BTW, the conflicts on this PR are nothing to worry about. They are just due to `git mv` operations that can be easily rebased onto master.

**Comment by gschaffner** [comment]
Note that the conflicts listed are nothing to worry about as they are primarily due to `git mv` operations that can be easily rebased onto the latest master.

**Comment by gschaffner** [comment]
Hi @jaxankey, have you seen this PR? It adds spinmob's dependencies to `setup.py` so that pip (or conda, I think) may install them. Spinmob does not currently tell pip about its dependencies---they are listed in the wiki and users must install them manually.

This PR also includes some changes to move spinmob towards using the best practices for Python packaging. The largest of these changes is moving source code into a `src` directory. This structure is used by many other projects:

https://github.com/pypa/pip
https://github.com/pytest-dev/pytest
https://github.com/pyca/cryptography
https://github.com/python-attrs/attrs
https://github.com/python-pillow/Pillow
https://github.com/twisted/twisted

For info about the benefits of this, check out https://blog.ionelmc.ro/2014/05/25/python-packaging/.

I can split the dependency changes into a separate PR if you do not want to make the other packaging changes.

**Comment by jaxankey** [comment]
I had looked at it and my _current_ thinking (based on very little research) on auto-installing dependencies is this: 
 - Not all packages are required for spinmob's basic functionality.
 - Not everyone wants to install dependencies via pip, specifically (including me). When trying to go "all pip" in the past, some packages did not install well (e.g., spyder) on all systems. In practice, conda is the most reliable way to install everything that can be installed by conda, which is why we recommend making a conda pass first, then using pip for the last few packages.

Regarding the directory structure, the proposed changes are incompatible with our workflow. Currently we check spinmob out directly from git into our site-packages directory, so that it's exceedingly fast and simple to make a fix and push it to our group without extensive testing (then do all the testing before "releasing"). I would be surprised if many people outside our group use the library, to be honest, and fast turnaround / feature implementation is essential for research progress. Gotta keep the barrier low so it actually happens (it's like leaving your guitar out of the case; put it away and it never gets played).

**Comment by gschaffner** [comment]
Gotcha. I 100% understand the reason to not change the directory structure.

W.r.t. dependencies (and please correct me if I am wrong): would adding the dependencies to `setup.py` conflict with your group's workflow? I am not too familiar with conda, but it seems that if dependencies are already being installed via conda then adding them to `setup.py` would not have any effect for you guys (but would be convenient for folks using pip primarily).

Setuptools also allows specifying optional dependencies in `setup.py`, e.g.

`setup(..., extras_require={"fit": ["lmfit"], "GUI": ["pyqtgraph>=0.11,<1"]})`

which would have no effect on pip unless one explicitly told it that they want to install optional dependencies: `pip install spinmob[fit,GUI]` vs. `pip install spinmob`. I expect it should not have an effect on conda either.

**Comment by jaxankey** [comment]
I think we could just try the normal auto-install dependencies. The less pip stuff to memorize, the better (if you're going to type "spinmob[fit,GUI]" you may as well type "spinmob lmfit pyqtgraph"). I believe pip will not mess with packages installed by conda.

If you submit a pull request with just these changes to setup.py, we can give it a shot for a few months. If we run into trouble, we can remove them later. I'm a little worried about changing things since we will deploy this to classrooms, in the winter term but let's just see what happens...

Cheers,
Jack
________________________________

**Pull request closed without merging**
